// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models.binding


case class DataRoot(dataCenter: Seq[models.binding.DataCenter] = Nil,
  id: Option[String] = None)


case class DataCenter(datacenteroption: Seq[scalaxb.DataRecord[models.binding.DataCenterOption]] = Nil,
  available: Option[BigInt] = None,
  desc: String,
  group: Option[String] = None,
  id1: Option[String] = None,
  isSimulation: Option[Boolean] = None,
  name: String,
  id: String)

trait DataCenterOption
trait DataCenterOption2 extends DataCenterOption

case class SimulationModel(runID: Seq[models.binding.RunID] = Nil,
  desc: String,
  name: String,
  id: String) extends DataCenterOption


case class RunID(mission: Seq[models.binding.Mission] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val FieldValue_Bx = attributes("@FieldValue_Bx").as[BigDecimal]
  lazy val FieldValue_By = attributes("@FieldValue_By").as[BigDecimal]
  lazy val FieldValue_Bz = attributes("@FieldValue_Bz").as[BigDecimal]
  lazy val GridCellSize_X = attributes("@GridCellSize_X").as[BigDecimal]
  lazy val GridCellSize_Y = attributes("@GridCellSize_Y").as[BigDecimal]
  lazy val GridCellSize_Z = attributes("@GridCellSize_Z").as[BigDecimal]
  lazy val LikelihoodRating = attributes("@LikelihoodRating").as[String]
  lazy val ReleaseDate = attributes("@ReleaseDate").as[javax.xml.datatype.XMLGregorianCalendar]
  lazy val SimulationType = attributes("@SimulationType").as[String]
  lazy val SolarUVFlux = attributes.get("@SolarUVFlux") map { _.as[BigDecimal] }
  lazy val Solar_Wind_Hu45Density = attributes("@Solar_Wind_H-Density").as[Double]
  lazy val Solar_Wind_Hu45FlowSpeed = attributes("@Solar_Wind_H-FlowSpeed").as[BigDecimal]
  lazy val Solar_Wind_Hu45Temperature = attributes("@Solar_Wind_H-Temperature").as[String]
  lazy val Solar_Wind_Heu45Density = attributes("@Solar_Wind_He-Density").as[String]
  lazy val Solar_Wind_Heu45FlowSpeed = attributes("@Solar_Wind_He-FlowSpeed").as[String]
  lazy val Solar_Wind_Heu45Temperature = attributes("@Solar_Wind_He-Temperature").as[String]
  lazy val Solar_Wind_electronsu45Density = attributes("@Solar_Wind_electrons-Density").as[String]
  lazy val Solar_Wind_electronsu45FlowSpeed = attributes("@Solar_Wind_electrons-FlowSpeed").as[String]
  lazy val Solar_Wind_electronsu45Temperature = attributes("@Solar_Wind_electrons-Temperature").as[String]
  lazy val TemporalDependence = attributes("@TemporalDependence").as[String]
  lazy val desc = attributes("@desc").as[String]
  lazy val name = attributes("@name").as[String]
  lazy val id = attributes("@id").as[String]
}



case class Mission(missionoption: Seq[scalaxb.DataRecord[models.binding.MissionOption]] = Nil,
  SimulatedRegion: Option[String] = None,
  att: Option[String] = None,
  available: Option[BigInt] = None,
  desc: String,
  name: String,
  target: Option[String] = None,
  targets: Option[String] = None,
  id: String) extends DataCenterOption2

trait MissionOption

case class MeasurementType(dataset: Seq[models.binding.Dataset] = Nil,
  desc: String,
  name: String,
  id: String) extends MissionOption


case class Instrument(dataset: Seq[models.binding.Dataset] = Nil,
  att: Option[String] = None,
  desc: String,
  name: String,
  id: String) extends MissionOption


case class Dataset(parameter: Seq[models.binding.Parameter] = Nil,
  att: Option[String] = None,
  dataSource: Option[String] = None,
  dataStart: Option[String] = None,
  dataStop: Option[String] = None,
  desc: Option[String] = None,
  maxSampling: Option[String] = None,
  name: String,
  rem_id: Option[String] = None,
  sampling: Option[String] = None,
  target: Option[String] = None,
  id: String) extends DataCenterOption2


case class Parameter(component: Seq[models.binding.Component] = Nil,
  desc: Option[String] = None,
  display_type: Option[String] = None,
  labels: Option[String] = None,
  mission: Option[String] = None,
  name: String,
  needsArgs: Option[BigInt] = None,
  parentID: Option[String] = None,
  size: Option[BigInt] = None,
  units: Option[String] = None,
  varValue: Option[String] = None,
  id: String)


case class Component(mission: Option[String] = None,
  name: String,
  parentID: Option[String] = None,
  varValue: Option[String] = None,
  id: String)

