// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models.binding


case class Database(name: String,
  description: Option[String] = None,
  databaseoption: Seq[scalaxb.DataRecord[String]] = Nil,
  methods: Seq[String] = Nil,
  tree: Seq[String] = Nil,
  protocol: Seq[String] = Nil,
  info: String,
  typeValue: models.binding.Databasetype,
  id: java.net.URI) extends ImpexconfigurationOption

trait DatabaseOption

case class Tool(name: String,
  description: Option[String] = None,
  tooloption: Seq[scalaxb.DataRecord[String]] = Nil,
  info: String) extends ImpexconfigurationOption

trait ToolOption

case class Impexconfiguration(impexconfigurationoption: scalaxb.DataRecord[models.binding.ImpexconfigurationOption]*)

trait ImpexconfigurationOption
trait Databasetype

object Databasetype {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): Databasetype = value match {
    case "simulation" => Simulation
    case "observation" => Observation

  }
}

case object Simulation extends Databasetype { override def toString = "simulation" }
case object Observation extends Databasetype { override def toString = "observation" }

