// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models.binding

import play.api.libs.json._
import play.api.libs.functional.syntax._
import java.net.URI


case class GetObsDataTreeResponseCLWEB(success: Option[Boolean] = None,
  Tree: java.net.URI)
