// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models.binding


trait Methods_SINP {
  def getDataPointValue(resourceID: String, variable: Option[Seq[String]], url_XYZ: java.net.URI, extraParams: Option[models.binding.ExtraParams_getDataPointValueSINP]): Either[scalaxb.Soap11Fault[Any], java.net.URI]
  def calculateDataPointValueFixedTime(resourceID: String, startTime: javax.xml.datatype.XMLGregorianCalendar, extraParams: Option[models.binding.ExtraParams_calculateDataPointValueFixedTime], url_XYZ: java.net.URI): Either[scalaxb.Soap11Fault[Any], java.net.URI]
  def calculateDataPointValue(resourceID: String, extraParams: Option[models.binding.ExtraParams_calculateDataPointValue], url_XYZ: java.net.URI): Either[scalaxb.Soap11Fault[Any], java.net.URI]
  def calculateDataPointValueSaturn(resourceID: String, extraParams: Option[models.binding.ExtraParams_calculateDataPointValueSaturn], url_XYZ: java.net.URI): Either[scalaxb.Soap11Fault[Any], java.net.URI]
  def calculateDataPointValueMercury(resourceID: String, extraParams: Option[models.binding.ExtraParams_calculateDataPointValueMercury], url_XYZ: java.net.URI): Either[scalaxb.Soap11Fault[Any], java.net.URI]
  def calculateDataPointValueJupiter(resourceID: String, extraParams: Option[models.binding.ExtraParams_calculateDataPointValueJupiter], url_XYZ: java.net.URI): Either[scalaxb.Soap11Fault[Any], java.net.URI]
  def calculateDataPointValueSpacecraft(resourceID: String, spacecraft_name: models.binding.SpacecraftTypeSINP, startTime: javax.xml.datatype.XMLGregorianCalendar, stopTime: javax.xml.datatype.XMLGregorianCalendar, sampling: javax.xml.datatype.Duration, extraParams: Option[models.binding.ExtraParams_calculateDataPointValueSpacecraft]): Either[scalaxb.Soap11Fault[Any], java.net.URI]
  def calculateFieldLine(resourceID: String, startTime: javax.xml.datatype.XMLGregorianCalendar, extraParams: Option[models.binding.ExtraParams_calculateFieldLine], url_XYZ: java.net.URI): Either[scalaxb.Soap11Fault[Any], java.net.URI]
  def calculateCube(resourceID: String, startTime: javax.xml.datatype.XMLGregorianCalendar, extraParams: Option[models.binding.ExtraParams_calculateCube], sampling: Option[Double], cube_size_array: Option[models.binding.Cube_size_array]): Either[scalaxb.Soap11Fault[Any], java.net.URI]
  def calculateCubeMercury(resourceID: String, extraParams: Option[models.binding.ExtraParams_calculateCubeMercury]): Either[scalaxb.Soap11Fault[Any], java.net.URI]
}




