// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models.binding


trait Methods_CLWEB {
  def getObsDataTree(): Either[scalaxb.Soap11Fault[Any], models.binding.GetObsDataTreeResponseCLWEB]
  def getTimeTablesList(userID: Option[String], password: Option[String]): Either[scalaxb.Soap11Fault[Any], models.binding.GetTimeTablesListResponse]
  def getParameter(startTime: String, stopTime: String, parameterID: String, sampling: Option[Float], userID: Option[String], password: Option[String], outputFormat: Option[models.binding.OutputFormat], timeFormat: Option[models.binding.TimeFormat], gzip: Option[BigInt]): Either[scalaxb.Soap11Fault[Any], models.binding.GetParameterResponse]
  def getTimeTable(userID: Option[String], password: Option[String], ttID: String): Either[scalaxb.Soap11Fault[Any], models.binding.GetTimeTableResponse]
}




