// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models

case class Database(name: String,
  description: Option[String] = None,
  databaseoption: Seq[DataRecord[String]] = Nil,
  methods: Option[String] = None,
  tree: String,
  protocol: Seq[String] = Nil,
  info: Option[String] = None,
  typeValue: Option[models.Databasetype] = None) extends ImpexconfigurationOption

trait DatabaseOption

case class Tool(name: String,
  description: Option[String] = None,
  tooloption: Seq[DataRecord[String]] = Nil,
  methods: String,
  protocol: Seq[String] = Nil,
  info: Option[String] = None) extends ImpexconfigurationOption

trait ToolOption

case class Impexconfiguration(impexconfigurationoption: DataRecord[models.ImpexconfigurationOption]*)

trait ImpexconfigurationOption
trait Databasetype

object Databasetype {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): Databasetype = value match {
    case "simulation" => Simulation
    case "observation" => Observation
  }
}

case object Simulation extends Databasetype { override def toString = "simulation" }
case object Observation extends Databasetype { override def toString = "observation" }

